name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'src/**'
      - 'lib/**'
      - 'dist/**'

permissions:
  contents: read
  packages: write

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build project (if needed)
        run: pnpm build || echo "No build script found"

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}